repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: no-commit-to-branch
        args:
          - --branch=main
          - --branch=master
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.2
    hooks:
      - id: check-yaml-schema
        types: [yaml]
        args: ["--schemafile", "schemas/brands_config.json"]
