name: pre-commit Lint

on:
  pull_request:

jobs:
  lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - run: pip install pre-commit
      - run: pre-commit run --hook-stage manual yamllint --all-files
