name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2
          
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.1

          
