name: Config Validation

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - run: pip install yamllint
      - run: yamllint --strict $(git ls-files '*.yaml' '*.yml')
